# Generated by Django 4.1.13 on 2023-12-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0002_task_user_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(),
        ),
    ]
